# Tavsiye (Oneri) Sistemleri Film Tavsiyesi

In [2]:
import pandas as pd

In [3]:
ratings=pd.read_csv('spark/ml-100k/u.data')

FileNotFoundError: [Errno 2] No such file or directory: 'spark/ml-100k/u.data'

In [4]:
ratings

NameError: name 'ratings' is not defined

In [5]:
import os
os.listdir()

['.ipynb_checkpoints',
 '1800.csv',
 'book.txt',
 'customer-orders.csv',
 'fakefriends.csv',
 'Marvel-graph.txt',
 'Marvel-names.txt',
 'ml-100k',
 'Recommender_System.ipynb',
 'regression.txt']

In [6]:
os.listdir('ml-100k')

['allbut.pl',
 'mku.sh',
 'README',
 'u.data',
 'u.genre',
 'u.info',
 'u.item',
 'u.occupation',
 'u.user',
 'u1.base',
 'u1.test',
 'u2.base',
 'u2.test',
 'u3.base',
 'u3.test',
 'u4.base',
 'u4.test',
 'u5.base',
 'u5.test',
 'ua.base',
 'ua.test',
 'ub.base',
 'ub.test']

In [7]:
import pandas as pd

ratings = pd.read_csv(
    "ml-100k/u.data",
    sep="\t",
    names=["user_id", "item_id", "rating", "timestamp"]
)

ratings.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [8]:
movies=pd.read_csv('ml-100k/u.item', encoding='iso-8859-1', sep='|', header=None, names=['movie_id', 'title'], usecols=range(2))

In [9]:
movies

      movie_id                                      title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [12]:
user=pd.read_csv('ml-100k/u.user', sep='|', header=None, names=['user_id','Age','Gender','Profession', 'Zipcode'])

In [13]:
user

     user_id  Age Gender     Profession Zipcode
0          1   24      M     technician   85711
1          2   53      F          other   94043
2          3   23      M         writer   32067
3          4   24      M     technician   43537
4          5   33      F          other   15213
..       ...  ...    ...            ...     ...
938      939   26      F        student   33319
939      940   32      M  administrator   02215
940      941   20      M        student   97229
941      942   48      F      librarian   78209
942      943   22      M        student   77841

[943 rows x 5 columns]

In [17]:
rating=pd.merge(movies,ratings)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [18]:
print("ratings:", ratings.shape, ratings.columns)
print("movies :", movies.shape, movies.columns)

display(ratings.head())
display(movies.head())

ratings: (100003, 4) Index(['user_id', 'item_id', 'rating', 'timestamp'], dtype='object')
movies : (1682, 2) Index(['movie_id', 'title'], dtype='object')

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [21]:
rating = rating.drop(columns=["movie_id"])

NameError: name 'rating' is not defined

In [22]:
rating = pd.merge(
    ratings,
    movies,
    left_on="item_id",
    right_on="movie_id",
    how="inner"
)

rating.head()

,user_id,item_id,rating,timestamp,movie_id,title
0,0,50,5,881250949,50,Star Wars (1977)
1,0,172,5,881250949,172,"Empire Strikes Back, The (1980)"
2,0,133,1,881250949,133,Gone with the Wind (1939)
3,196,242,3,881250949,242,Kolya (1996)
4,186,302,3,891717742,302,L.A. Confidential (1997)

In [23]:
rating=pd.merge(rating,user)

In [24]:
rating

,user_id,item_id,rating,timestamp,movie_id,title,Age,Gender,Profession,Zipcode
0,196,242,3,881250949,242,Kolya (1996),49,M,writer,55105
1,186,302,3,891717742,302,L.A. Confidential (1997),39,F,executive,00000
2,22,377,1,878887116,377,Heavyweights (1994),25,M,writer,40206
3,244,51,2,880606923,51,Legends of the Fall (1994),28,M,technician,80525
4,166,346,1,886397596,346,Jackie Brown (1997),47,M,educator,55113
...,...,...,...,...,...,...,...,...,...,...
99995,880,476,3,880175444,476,"First Wives Club, The (1996)",13,M,student,83702
99996,716,204,5,879795543,204,Back to the Future (1985),36,F,administrator,44265
99997,276,1090,1,874795795,1090,Sliver (1993),21,M,student,95064
99998,13,225,2,882399156,225,101 Dalmatians (1996),47,M,educator,29206
99999,12,203,3,879959583,203,Unforgiven (1992),28,F,other,06405

In [26]:
print("ratings:", ratings.shape, ratings.columns)
print("user :", user.shape, user.columns)

display(ratings.head())
display(user.head())

ratings: (100003, 4) Index(['user_id', 'item_id', 'rating', 'timestamp'], dtype='object')
user : (943, 5) Index(['user_id', 'Age', 'Gender', 'Profession', 'Zipcode'], dtype='object')

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

   user_id  Age Gender  Profession Zipcode
0        1   24      M  technician   85711
1        2   53      F       other   94043
2        3   23      M      writer   32067
3        4   24      M  technician   43537
4        5   33      F       other   15213

In [27]:
rating.title.value_counts()

title
Star Wars (1977)                   583
Contact (1997)                     509
Fargo (1996)                       508
Return of the Jedi (1983)          507
Liar Liar (1997)                   485
                                  ...
Leopard Son, The (1996)              1
Stefano Quantestorie (1993)          1
Quartier Mozart (1992)               1
Reluctant Debutante, The (1958)      1
Dadetown (1995)                      1
Name: count, Length: 1664, dtype: int64

In [29]:
import numpy as np

In [30]:
mg=rating.groupby('title').agg({'rating' :[np.size,np.sum,np.mean]})

C:\Users\Kullanıcı\AppData\Local\Temp\ipykernel_52888\1149636805.py:1: FutureWarning: The provided callable <function sum at 0x00000214A23D8040> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  mg=rating.groupby('title').agg({'rating' :[np.size,np.sum,np.mean]})
C:\Users\Kullanıcı\AppData\Local\Temp\ipykernel_52888\1149636805.py:1: FutureWarning: The provided callable <function mean at 0x00000214A23D9440> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mg=rating.groupby('title').agg({'rating' :[np.size,np.sum,np.mean]})

In [31]:
mg = (rating.groupby('title')['rating']
      .agg(count='count', sum='sum', mean='mean')
      .reset_index())

mg.head()

                       title  count  sum      mean
0  'Til There Was You (1997)      9   21  2.333333
1               1-900 (1994)      5   13  2.600000
2      101 Dalmatians (1996)    109  317  2.908257
3        12 Angry Men (1957)    125  543  4.344000
4                 187 (1997)     41  124  3.024390

In [32]:
pm=mg.sort_values(('rating','mean'), ascending=False)

KeyError: ('rating', 'mean')

In [33]:
import pandas as pd

# Film bazında sayım ve ortalama
mg = (rating.groupby('title')['rating']
      .agg(size='count', mean='mean')
      .reset_index())

# Ortalama puana göre sırala (yüksekten düşüğe)
pm = mg.sort_values('mean', ascending=False)

pm.head(20)

                                                  title  size      mean
1472                     They Made Me a Criminal (1939)     1  5.000000
944          Marlene Dietrich: Shadow and Light (1996)      1  5.000000
1273               Saint of Fort Washington, The (1993)     2  5.000000
1359                      Someone Else's America (1995)     1  5.000000
1387                                    Star Kid (1997)     3  5.000000
633                       Great Day in Harlem, A (1994)     1  5.000000
30                                 Aiqing wansui (1994)     1  5.000000
1277                          Santa with Muscles (1996)     2  5.000000
1172                                 Prefontaine (1997)     3  5.000000
462   Entertaining Angels: The Dorothy Day Story (1996)     1  5.000000
1130                             Pather Panchali (1955)     8  4.625000
1357                           Some Mother's Son (1996)     2  4.500000
956              Maya Lin: A Strong Clear Vision (1994)     4  4.500000
79                                          Anna (1996)     2  4.500000
472                                      Everest (1998)     2  4.500000
318                               Close Shave, A (1995)   112  4.491071
1281                            Schindler's List (1993)   298  4.466443
1652                         Wrong Trousers, The (1993)   118  4.466102
273                                   Casablanca (1942)   243  4.456790
1597  Wallace & Gromit: The Best of Aardman Animatio...    67  4.447761

In [35]:
mg = (rating.groupby('title')['rating']
      .agg(size='count', sum='sum', mean='mean')
      .reset_index())

pm = mg.sort_values('mean', ascending=False)

gs = pm['sum'].sum()     # ✅ toplam rating puanı
gc = pm['size'].sum()    # ✅ toplam oy sayısı
gmean = gs / gc          # ✅ genel ortalama

print("Toplam puan (sum):", gs)
print("Toplam oy (count):", gc)
print("Genel ortalama:", gmean)

Toplam puan (sum): 352986
Toplam oy (count): 100000
Genel ortalama: 3.52986

In [36]:
gs=pm['rating']['sum'].sum()

KeyError: 'rating'

In [37]:
import pandas as pd
import numpy as np

# rating DataFrame'in hazır olduğunu varsayıyorum:
# rating kolonları: ['user_id','item_id','rating','timestamp','title'] (veya en azından 'title' ve 'rating' olmalı)

# 1) Film bazında istatistikler (popülerlik + kalite)
mg = (rating.groupby('title')['rating']
      .agg(size='count', sum='sum', mean='mean')
      .reset_index())

# 2) Ortalama puana göre sırala (istersen önce filtrele)
pm = mg.sort_values('mean', ascending=False)

# 3) Toplam puan (tüm filmlerin sum toplamı)
gs = pm['sum'].sum()

# 4) Yüzde katkı: her filmin toplam puan içindeki payı (%)
pm['percentage'] = (pm['sum'] / gs) * 100

# 5) Rank: en yüksek yüzde = en iyi rank (1 en iyi)
pm['rank'] = pm['percentage'].rank(ascending=False, method='dense')

# 6) En popüler (rank küçükten büyüğe)
top_popular = pm.sort_values('rank', ascending=True)

# Göster
top_popular.head(20)

                                 title  size   sum      mean  percentage  rank
1398                  Star Wars (1977)   583  2541  4.358491    0.719859   1.0
498                       Fargo (1996)   508  2111  4.155512    0.598041   2.0
1234         Return of the Jedi (1983)   507  2032  4.007890    0.575660   3.0
333                     Contact (1997)   509  1936  3.803536    0.548464   4.0
1205    Raiders of the Lost Ark (1981)   420  1786  4.252381    0.505969   5.0
612              Godfather, The (1972)   413  1769  4.283293    0.501153   6.0
460        English Patient, The (1996)   481  1759  3.656965    0.498320   7.0
1523                  Toy Story (1995)   452  1753  3.878319    0.496620   8.0
1329  Silence of the Lambs, The (1991)   390  1673  4.289744    0.473956   9.0
1284                     Scream (1996)   478  1645  3.441423    0.466024  10.0
1190               Pulp Fiction (1994)   394  1600  4.060914    0.453276  11.0
32                Air Force One (1997)   431  1565  3.631090    0.443360  12.0
456    Empire Strikes Back, The (1980)   367  1543  4.204360    0.437128  13.0
860                   Liar Liar (1997)   485  1531  3.156701    0.433728  14.0
1543             Twelve Monkeys (1995)   392  1489  3.798469    0.421830  15.0
1500                    Titanic (1997)   350  1486  4.245714    0.420980  16.0
744      Independence Day (ID4) (1996)   429  1475  3.438228    0.417864  17.0
293                 Chasing Amy (1997)   379  1455  3.839050    0.412198  18.0
780               Jerry Maguire (1996)   384  1425  3.710938    0.403699  19.0
1251                  Rock, The (1996)   378  1396  3.693122    0.395483  20.0