# Tavsiye (Oneri) Sistemleri Film Tavsiyesi

In [1]:
import pandas as pd

In [2]:
ratings=pd.read_csv('spark/ml-100k/u.data')

FileNotFoundError: [Errno 2] No such file or directory: 'spark/ml-100k/u.data'

In [3]:
ratings

NameError: name 'ratings' is not defined

In [4]:


import os
os.listdir()

['.ipynb_checkpoints',
 '1800.csv',
 'book.txt',
 'customer-orders.csv',
 'fakefriends.csv',
 'Marvel-graph.txt',
 'Marvel-names.txt',
 'ml-100k',
 'Recommender_System.ipynb',
 'regression.txt',
 'RSMatrixFactorization.ipynb']

In [5]:

os.listdir('ml-100k')

['allbut.pl',
 'mku.sh',
 'README',
 'u.data',
 'u.genre',
 'u.info',
 'u.item',
 'u.occupation',
 'u.user',
 'u1.base',
 'u1.test',
 'u2.base',
 'u2.test',
 'u3.base',
 'u3.test',
 'u4.base',
 'u4.test',
 'u5.base',
 'u5.test',
 'ua.base',
 'ua.test',
 'ub.base',
 'ub.test']

In [6]:



import pandas as pd

ratings = pd.read_csv(
    "ml-100k/u.data",
    sep="\t",
    names=["user_id", "item_id", "rating", "timestamp"]
)

ratings.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [7]:
movies=pd.read_csv('ml-100k/u.item', encoding='iso-8859-1', sep='|', header=None, names=['movie_id', 'title'], usecols=range(2))

In [8]:
movies

      movie_id                                      title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [9]:
user=pd.read_csv('ml-100k/u.user', sep='|', header=None, names=['user_id','Age','Gender','Profession', 'Zipcode'])

In [10]:
user

     user_id  Age Gender     Profession Zipcode
0          1   24      M     technician   85711
1          2   53      F          other   94043
2          3   23      M         writer   32067
3          4   24      M     technician   43537
4          5   33      F          other   15213
..       ...  ...    ...            ...     ...
938      939   26      F        student   33319
939      940   32      M  administrator   02215
940      941   20      M        student   97229
941      942   48      F      librarian   78209
942      943   22      M        student   77841

[943 rows x 5 columns]

In [11]:
rating=pd.merge(movies,ratings)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [ ]:
print("ratings:", ratings.shape, ratings.columns)
print("movies :", movies.shape, movies.columns)

display(ratings.head())
display(movies.head())

In [12]:
rating = rating.drop(columns=["movie_id"])

NameError: name 'rating' is not defined

In [13]:
rating = pd.merge(
    ratings,
    movies,
    left_on="item_id",
    right_on="movie_id",
    how="inner"
)

rating.head()

,user_id,item_id,rating,timestamp,movie_id,title
0,0,50,5,881250949,50,Star Wars (1977)
1,0,172,5,881250949,172,"Empire Strikes Back, The (1980)"
2,0,133,1,881250949,133,Gone with the Wind (1939)
3,196,242,3,881250949,242,Kolya (1996)
4,186,302,3,891717742,302,L.A. Confidential (1997)

In [14]:
rating=pd.merge(rating,user)

In [15]:
rating

,user_id,item_id,rating,timestamp,movie_id,title,Age,Gender,Profession,Zipcode
0,196,242,3,881250949,242,Kolya (1996),49,M,writer,55105
1,186,302,3,891717742,302,L.A. Confidential (1997),39,F,executive,00000
2,22,377,1,878887116,377,Heavyweights (1994),25,M,writer,40206
3,244,51,2,880606923,51,Legends of the Fall (1994),28,M,technician,80525
4,166,346,1,886397596,346,Jackie Brown (1997),47,M,educator,55113
...,...,...,...,...,...,...,...,...,...,...
99995,880,476,3,880175444,476,"First Wives Club, The (1996)",13,M,student,83702
99996,716,204,5,879795543,204,Back to the Future (1985),36,F,administrator,44265
99997,276,1090,1,874795795,1090,Sliver (1993),21,M,student,95064
99998,13,225,2,882399156,225,101 Dalmatians (1996),47,M,educator,29206
99999,12,203,3,879959583,203,Unforgiven (1992),28,F,other,06405

In [16]:
print("ratings:", ratings.shape, ratings.columns)
print("user :", user.shape, user.columns)

display(ratings.head())
display(user.head())

ratings: (100003, 4) Index(['user_id', 'item_id', 'rating', 'timestamp'], dtype='object')
user : (943, 5) Index(['user_id', 'Age', 'Gender', 'Profession', 'Zipcode'], dtype='object')

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

   user_id  Age Gender  Profession Zipcode
0        1   24      M  technician   85711
1        2   53      F       other   94043
2        3   23      M      writer   32067
3        4   24      M  technician   43537
4        5   33      F       other   15213

In [17]:
mf=rating.pivot_table(index=['user_id'], columns=['title'], values='rating')

In [18]:
mf.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN

In [19]:
swr=mf['Star Wars (1977)']

In [20]:
swr.value_counts()

Star Wars (1977)
5.0    325
4.0    176
3.0     57
2.0     16
1.0      9
Name: count, dtype: int64

In [21]:
mf[['Star Wars (1977)', '101 Dalmatians (1996)']].corr()

title                  Star Wars (1977)  101 Dalmatians (1996)
title
Star Wars (1977)               1.000000               0.211132
101 Dalmatians (1996)          0.211132               1.000000

In [22]:
sm=mf.corrwith(swr)

C:\Anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:3057: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2914: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Anaconda3\Lib\site-packages\numpy\lib\_function_base_impl.py:2914: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

In [23]:
sm.sort_values(ascending=False)

title
Hollow Reed (1996)                         1.0
Commandments (1997)                        1.0
Cosi (1996)                                1.0
No Escape (1994)                           1.0
Stripes (1981)                             1.0
                                          ...
Wonderland (1997)                          NaN
Wooden Man's Bride, The (Wu Kui) (1994)    NaN
Yankee Zulu (1994)                         NaN
You So Crazy (1994)                        NaN
Á köldum klaka (Cold Fever) (1994)         NaN
Length: 1664, dtype: float64

In [24]:
import numpy as np

In [25]:
mstats=rating.groupby('title').agg({'rating':[np.size, np.mean]})

C:\Users\Kullanıcı\AppData\Local\Temp\ipykernel_52772\707841785.py:1: FutureWarning: The provided callable <function mean at 0x0000018AAFA399E0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mstats=rating.groupby('title').agg({'rating':[np.size, np.mean]})

In [26]:
mstats.head()

                          rating
                            size      mean
title
'Til There Was You (1997)      9  2.333333
1-900 (1994)                   5  2.600000
101 Dalmatians (1996)        109  2.908257
12 Angry Men (1957)          125  4.344000
187 (1997)                    41  3.024390

In [27]:
pm=mstats[mstats['rating']['size']>100]

In [28]:
smdata=pd.DataFrame(sm, columns=['similarity'])

In [29]:
smdata

                                       similarity
title
'Til There Was You (1997)                0.872872
1-900 (1994)                            -0.645497
101 Dalmatians (1996)                    0.211132
12 Angry Men (1957)                      0.184289
187 (1997)                               0.027398
...                                           ...
Young Guns II (1990)                     0.228615
Young Poisoner's Handbook, The (1995)   -0.007374
Zeus and Roxanne (1997)                  0.818182
unknown                                  0.723123
Á köldum klaka (Cold Fever) (1994)            NaN

[1664 rows x 1 columns]

In [30]:
pm.columns=pm.columns.get_level_values(0)
df=pm.join(smdata)

In [31]:
df.sort_values(['similarity'], ascending=False

,rating,rating,similarity
title,,,
Star Wars (1977),583,4.358491,1.000000
"Empire Strikes Back, The (1980)",367,4.204360,0.747981
Return of the Jedi (1983),507,4.007890,0.672556
Raiders of the Lost Ark (1981),420,4.252381,0.536117
Austin Powers: International Man of Mystery (1997),130,3.246154,0.377433
...,...,...,...
"Edge, The (1997)",113,3.539823,-0.127167
As Good As It Gets (1997),112,4.196429,-0.130466
Crash (1996),128,2.546875,-0.148507
G.I. Jane (1997),175,3.360000,-0.176734
"First Wives Club, The (1996)",160,3.018750,-0.194496