## Laptop Price Prediction

<img src= "https://www.icotech.com.tr/upload/icotech-ds16-cift-ekranli-laptop-intel-i7-32-gb-ram-1-tb-ssd-hdd-5-2477.jpg">

Dizüstü bilgisayar fiyatlarını özelliklerine göre tahmin etmej için regresyon odeli geliştirilecektir. Bu modelin amacı doğru ve güvenilir fiyat bilgilerini sağlayarak kullanıcılara ve satıcılara yardımcı olmaktır.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('laptop_data.csv', index_col=0)

In [3]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   object
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   object
 10  Price             1303 non-null   float64
dtypes: float64(2), object(9)
memory usage: 122.2+ KB

In [5]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [6]:
df.shape

(1303, 11)

In [7]:
df['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [8]:
df.TypeName.value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64

In [9]:
df.ScreenResolution.value_counts()

ScreenResolution
Full HD 1920x1080                                507
1366x768                                         281
IPS Panel Full HD 1920x1080                      230
IPS Panel Full HD / Touchscreen 1920x1080         53
Full HD / Touchscreen 1920x1080                   47
1600x900                                          23
Touchscreen 1366x768                              16
Quad HD+ / Touchscreen 3200x1800                  15
IPS Panel 4K Ultra HD 3840x2160                   12
IPS Panel 4K Ultra HD / Touchscreen 3840x2160     11
4K Ultra HD / Touchscreen 3840x2160               10
4K Ultra HD 3840x2160                              7
Touchscreen 2560x1440                              7
IPS Panel 1366x768                                 7
IPS Panel Quad HD+ / Touchscreen 3200x1800         6
IPS Panel Retina Display 2560x1600                 6
IPS Panel Retina Display 2304x1440                 6
Touchscreen 2256x1504                              6
IPS Panel Touchscreen 2560x1440                    5
IPS Panel Retina Display 2880x1800                 4
IPS Panel Touchscreen 1920x1200                    4
1440x900                                           4
IPS Panel 2560x1440                                4
IPS Panel Quad HD+ 2560x1440                       3
Quad HD+ 3200x1800                                 3
1920x1080                                          3
Touchscreen 2400x1600                              3
2560x1440                                          3
IPS Panel Touchscreen 1366x768                     3
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
IPS Panel Full HD 2160x1440                        2
IPS Panel Quad HD+ 3200x1800                       2
IPS Panel Retina Display 2736x1824                 1
IPS Panel Full HD 1920x1200                        1
IPS Panel Full HD 2560x1440                        1
IPS Panel Full HD 1366x768                         1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / Quad HD+ 3200x1800                   1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Touchscreen 2400x1600                    1
Name: count, dtype: int64

In [10]:
import re
def extract_resolution(resolution_string):
    match = re.search(r'(\d+x\d+)', resolution_string)
    return match.group(1) if match else None

df['Resolution'] = df['ScreenResolution'].apply(extract_resolution)

In [11]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Resolution
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,2560x1600
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,1440x900
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,1920x1080
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,2880x1800
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,2560x1600

In [12]:
def extract_ghz(cpu_string):
    match = re.search(r'(\d+(\.\d+)?)GHz', cpu_string)
    return float(match.group(1)) if match else None 

df['GHz'] = df['Cpu'].apply(extract_ghz)

In [13]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Resolution,GHz
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,2560x1600,2.3
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,1440x900,1.8
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,1920x1080,2.5
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,2880x1800,2.7
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,2560x1600,3.1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   object
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   object
 10  Price             1303 non-null   float64
 11  Resolution        1303 non-null   object
 12  GHz               1303 non-null   float64
dtypes: float64(3), object(10)
memory usage: 142.5+ KB

In [15]:
df.Ram.value_counts()

Ram
8GB     619
4GB     375
16GB    200
6GB      41
12GB     25
2GB      22
32GB     17
24GB      3
64GB      1
Name: count, dtype: int64

In [16]:
df['Ram'] = df['Ram'].str.replace('GB','').astype("int32")

In [17]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
Resolution          0
GHz                 0
dtype: int64

In [18]:
df.Memory.value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [19]:
df['Memory'] = df['Memory'].str.replace("2TB","2048GB")
df['Memory'] = df['Memory'].str.replace(".0TB","024GB")
df['Memory'] = df['Memory'].str.replace("TB","024GB")

In [20]:
df.Memory.value_counts()

Memory
256GB SSD                           412
1024GB HDD                          224
500GB HDD                           132
512GB SSD                           118
128GB SSD +  1024GB HDD              94
128GB SSD                            76
256GB SSD +  1024GB HDD              73
32GB Flash Storage                   38
2048GB HDD                           16
64GB Flash Storage                   15
512GB SSD +  1024GB HDD              14
1024GB SSD                           14
256GB SSD +  2048GB HDD              10
1024GB Hybrid                         9
256GB Flash Storage                   8
16GB Flash Storage                    7
32GB SSD                              6
180GB SSD                             5
128GB Flash Storage                   4
512GB SSD +  2048GB HDD               3
16GB SSD                              3
512GB Flash Storage                   2
1024GB SSD +  1024GB HDD              2
256GB SSD +  500GB HDD                2
128GB SSD +  2048GB HDD               2
256GB SSD +  256GB SSD                2
512GB SSD +  256GB SSD                1
512GB SSD +  512GB SSD                1
64GB Flash Storage +  1024GB HDD      1
1024GB HDD +  1024GB HDD              1
32GB HDD                              1
64GB SSD                              1
128GB HDD                             1
240GB SSD                             1
8GB SSD                               1
508GB Hybrid                          1
512GB SSD +  1024GB Hybrid            1
256GB SSD +  1024GB Hybrid            1
Name: count, dtype: int64

256GB SSD +  256GB SSD                2
512GB SSD +  256GB SSD                1
512GB SSD +  512GB SSD                1
1024GB HDD +  1024GB HDD              1

In [22]:
df['Memory'] = df['Memory'].str.replace("256GB SSD +  256GB SSD","512GB SSD")
df['Memory'] = df['Memory'].str.replace("512GB SSD +  256GB SSD","768GB SSD")
df['Memory'] = df['Memory'].str.replace("512GB SSD +  512GB SSD","1024GB SSD")
df['Memory'] = df['Memory'].str.replace("1024GB HDD +  1024GB HDD","2048GB SSD")

In [23]:
df['SSD']=0
df['HDD']=0
df['Flash_Storage']=0
df['hYBRİD']=0

In [24]:
def extract_memory_sizes(memory_string):

    if 'SSD' in memory_string:
        size_match=re.search(r'\b(\d+)GB\s+SSD\b', memory_string)
        if size_match:
            df.loc[df['Memory']==memory_string, 'SSD'] = size_match.group(1)
    if 'HDD' in memory_string:
        size_match=re.search(r'\b(\d+)GB\s+HDD\b', memory_string)
        if size_match:
            df.loc[df['Memory']==memory_string, 'HDD'] = size_match.group(1)

    if 'Flash Storage' in memory_string:
        size_match=re.search(r'\b(\d+)GB\s+Flash Storage\b', memory_string)
        if size_match:
            df.loc[df['Memory']==memory_string, 'Flash_Storage'] = size_match.group(1)


    if 'Flash Storage' in memory_string:
        size_match=re.search(r'\b(\d+)GB\s+Hybrid\b', memory_string)
        if size_match:
            df.loc[df['Memory']==memory_string, 'Hybrid'] = size_match.group(1)
            
        
for memory in df['Memory']:
    extract_memory_sizes(memory)

C:\Users\Kullanıcı\AppData\Local\Temp\ipykernel_53140\2656114412.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '128' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Memory']==memory_string, 'SSD'] = size_match.group(1)
C:\Users\Kullanıcı\AppData\Local\Temp\ipykernel_53140\2656114412.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '128' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Memory']==memory_string, 'Flash_Storage'] = size_match.group(1)
C:\Users\Kullanıcı\AppData\Local\Temp\ipykernel_53140\2656114412.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '500' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Memory']==memory_string, 'HDD'] = size_match.group(1)

In [25]:
df.tail()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Resolution,GHz,SSD,HDD,Flash_Storage,hYBRİD
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.64,1920x1080,2.5,128,0,0,0
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.72,3200x1800,2.5,512,0,0,0
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.12,1366x768,1.6,0,0,64,0
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1024GB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.92,1366x768,2.5,0,1024,0,0
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.32,1366x768,1.6,0,500,0,0

In [28]:
df['SSD']=df['SSD'].astype('int32')
df['HDD']=df['HDD'].astype('int32')
df['Flash_Storage']=df['Flash_Storage'].astype('int32')
df['hYBRİD']=df['hYBRİD'].astype('int32')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303 entries, 0 to 1302
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int32
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   object
 10  Price             1303 non-null   float64
 11  Resolution        1303 non-null   object
 12  GHz               1303 non-null   float64
 13  SSD               1303 non-null   int32
 14  HDD               1303 non-null   int32
 15  Flash_Storage     1303 non-null   int32
 16  hYBRİD            1303 non-null   int32
dtypes: float64(3), int32(5), object(9)
memory usage: 157.8+ KB

In [30]:
df.OpSys.value_counts()

OpSys
Windows 10      1072
No OS             66
Linux             62
Windows 7         45
Chrome OS         27
macOS             13
Mac OS X           8
Windows 10 S       8
Android            2
Name: count, dtype: int64

In [31]:
df['OpSys']=df['OpSys'].replace('Windows 10 S', 'Windows 10')
df['OpSys']=df['OpSys'].replace('Mac OS X', 'macOS')

In [32]:
df.OpSys.value_counts()

OpSys
Windows 10    1080
No OS           66
Linux           62
Windows 7       45
Chrome OS       27
macOS           21
Android          2
Name: count, dtype: int64

In [35]:
df['Weight']=df['Weight'].str.rstrip("kg").astype(float)

In [34]:
df.head(1)

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Resolution,GHz,SSD,HDD,Flash_Storage,hYBRİD
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,2560x1600,2.3,128,0,0,0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303 entries, 0 to 1302
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int32
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   float64
 10  Price             1303 non-null   float64
 11  Resolution        1303 non-null   object
 12  GHz               1303 non-null   float64
 13  SSD               1303 non-null   int32
 14  HDD               1303 non-null   int32
 15  Flash_Storage     1303 non-null   int32
 16  hYBRİD            1303 non-null   int32
dtypes: float64(4), int32(5), object(8)
memory usage: 157.8+ KB

In [39]:
abs(df.corr(numeric_only=True)['Price']).sort_values(ascending=False)

Price            1.000000
Ram              0.743007
SSD              0.641228
GHz              0.430293
Weight           0.210370
HDD              0.093032
Inches           0.068197
Flash_Storage    0.040511
hYBRİD                NaN
Name: Price, dtype: float64

In [40]:
df['IPS'] = df['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)
df['Touchscreen'] = df['ScreenResolution'].apply(lambda x: 1 if 'Touchscreen' in x else 0)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1303 entries, 0 to 1302
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int32
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   float64
 10  Price             1303 non-null   float64
 11  Resolution        1303 non-null   object
 12  GHz               1303 non-null   float64
 13  SSD               1303 non-null   int32
 14  HDD               1303 non-null   int32
 15  Flash_Storage     1303 non-null   int32
 16  hYBRİD            1303 non-null   int32
 17  IPS               1303 non-null   int64
 18  Touchscreen       1303 non-null   int64
dtypes: float64(4), int32(5), int64(2), object(8)
memory usage: 178.1+ KB

In [44]:
x=df.drop(['Price','ScreenResolution','Cpu','Gpu','Memory', 'Resolution'], axis=1)
y=df[['Price']]

In [49]:
# ===============================
# 1. GEREKLİ KÜTÜPHANELER
# ===============================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from xgboost import XGBRegressor


# ===============================
# 2. ANA FONKSİYON
# ===============================

def regression_model_comparison(X, y, test_size=0.2, random_state=42):
    """
    Birden fazla regresyon algoritmasını tek seferde eğitir,
    doğruluk metriklerini hesaplar ve karşılaştırır.
    """

    # ---------------------------
    # Train / Test Split
    # ---------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )

    # ---------------------------
    # Model Tanımları
    # ---------------------------
    models = {
        "Linear Regression": LinearRegression(),

        "Ridge Regression": Pipeline([
            ("scaler", StandardScaler()),
            ("model", Ridge(alpha=1.0))
        ]),

        "Lasso Regression": Pipeline([
            ("scaler", StandardScaler()),
            ("model", Lasso(alpha=0.01))
        ]),

        "ElasticNet": Pipeline([
            ("scaler", StandardScaler()),
            ("model", ElasticNet(alpha=0.01, l1_ratio=0.5))
        ]),

        "KNN Regressor": Pipeline([
            ("scaler", StandardScaler()),
            ("model", KNeighborsRegressor(n_neighbors=5))
        ]),

        "Decision Tree": DecisionTreeRegressor(
            max_depth=10,
            random_state=random_state
        ),

        "Random Forest": RandomForestRegressor(
            n_estimators=200,
            max_depth=15,
            random_state=random_state,
            n_jobs=-1
        ),

        "Extra Trees": ExtraTreesRegressor(
            n_estimators=200,
            random_state=random_state,
            n_jobs=-1
        ),

        "Gradient Boosting": GradientBoostingRegressor(
            n_estimators=200,
            learning_rate=0.05,
            max_depth=4,
            random_state=random_state
        ),

        "AdaBoost": AdaBoostRegressor(
            n_estimators=200,
            learning_rate=0.05,
            random_state=random_state
        ),

        "XGBoost": XGBRegressor(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=random_state,
            n_jobs=-1
        )
    }

    # ---------------------------
    # Sonuçları Tutacağımız Liste
    # ---------------------------
    results = []

    # ---------------------------
    # Model Eğitimi & Değerlendirme
    # ---------------------------
    for model_name, model in models.items():
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)

        r2 = r2_score(y_test, predictions)
        rmse = np.sqrt(mean_squared_error(y_test, predictions))
        mae = mean_absolute_error(y_test, predictions)

        results.append({
            "Model": model_name,
            "R2 Score": r2,
            "RMSE": rmse,
            "MAE": mae
        })

    # ---------------------------
    # Sonuç Tablosu
    # ---------------------------
    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values("R2 Score", ascending=False).reset_index(drop=True)

    return results_df