# Data Imputation - boş verileri doldurma

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('ExampleData.csv')

In [4]:
df

    Height   YOE  Salary
0    175.0   3.0     6.0
1    168.0   4.0     9.0
2    160.0  10.0    18.0
3      NaN  15.0    25.0
4    161.0   NaN    50.0
5    162.0   5.0    10.0
6    180.0   6.0    11.0
7      NaN   7.0     NaN
8    172.0   8.0    12.0
9    170.0   9.0    14.0
10   175.0   3.0     6.0
11   168.0   4.0     9.0
12   160.0  10.0    18.0
13     NaN  15.0    25.0
14   161.0   NaN    50.0
15   162.0   5.0    10.0
16   180.0   6.0    11.0
17     NaN   7.0     NaN
18   172.0   8.0    12.0
19   170.0   9.0    14.0
20   161.0   NaN    50.0
21   162.0   5.0    10.0
22   180.0   6.0    11.0
23     NaN   7.0     NaN
24   175.0   3.0     6.0

In [ ]:
#bos verileri doldurmanin yollari, orta deger en yakin komsular, regression

# Imputation - bos verileri doldurmanin yollari, orta deger, en yakin komsulari, resgression

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
imp=SimpleImputer(strategy='mean')

In [10]:
yenidata=imp.fit_transform(df)

In [11]:
pd.DataFrame(yenidata)

        0          1          2
0   175.0   3.000000   6.000000
1   168.0   4.000000   9.000000
2   160.0  10.000000  18.000000
3   168.7  15.000000  25.000000
4   161.0   7.045455  50.000000
5   162.0   5.000000  10.000000
6   180.0   6.000000  11.000000
7   168.7   7.000000  17.590909
8   172.0   8.000000  12.000000
9   170.0   9.000000  14.000000
10  175.0   3.000000   6.000000
11  168.0   4.000000   9.000000
12  160.0  10.000000  18.000000
13  168.7  15.000000  25.000000
14  161.0   7.045455  50.000000
15  162.0   5.000000  10.000000
16  180.0   6.000000  11.000000
17  168.7   7.000000  17.590909
18  172.0   8.000000  12.000000
19  170.0   9.000000  14.000000
20  161.0   7.045455  50.000000
21  162.0   5.000000  10.000000
22  180.0   6.000000  11.000000
23  168.7   7.000000  17.590909
24  175.0   3.000000   6.000000

In [12]:
from sklearn.impute import KNNImputer

In [13]:
knn=KNNImputer()

In [15]:
dolu=knn.fit_transform(df)

In [16]:
pd.DataFrame(dolu)

        0     1     2
0   175.0   3.0   6.0
1   168.0   4.0   9.0
2   160.0  10.0  18.0
3   166.4  15.0  25.0
4   161.0  11.8  50.0
5   162.0   5.0  10.0
6   180.0   6.0  11.0
7   176.8   7.0  11.4
8   172.0   8.0  12.0
9   170.0   9.0  14.0
10  175.0   3.0   6.0
11  168.0   4.0   9.0
12  160.0  10.0  18.0
13  166.4  15.0  25.0
14  161.0  11.8  50.0
15  162.0   5.0  10.0
16  180.0   6.0  11.0
17  176.8   7.0  11.4
18  172.0   8.0  12.0
19  170.0   9.0  14.0
20  161.0  11.8  50.0
21  162.0   5.0  10.0
22  180.0   6.0  11.0
23  176.8   7.0  11.4
24  175.0   3.0   6.0

In [17]:
from sklearn.experimental import enable_iterative_imputer

In [18]:
from sklearn.impute import IterativeImputer

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
lr=LinearRegression()

In [22]:
imp=IterativeImputer(estimator=lr)

In [23]:
lrdata=imp.fit_transform(df)

In [24]:
pd.DataFrame(lrdata)

             0          1         2
0   175.000000   3.000000   6.00000
1   168.000000   4.000000   9.00000
2   160.000000  10.000000  18.00000
3   165.275222  15.000000  25.00000
4   161.000000  31.706376  50.00000
5   162.000000   5.000000  10.00000
6   180.000000   6.000000  11.00000
7   169.720689   7.000000  12.40191
8   172.000000   8.000000  12.00000
9   170.000000   9.000000  14.00000
10  175.000000   3.000000   6.00000
11  168.000000   4.000000   9.00000
12  160.000000  10.000000  18.00000
13  165.275222  15.000000  25.00000
14  161.000000  31.706376  50.00000
15  162.000000   5.000000  10.00000
16  180.000000   6.000000  11.00000
17  169.720689   7.000000  12.40191
18  172.000000   8.000000  12.00000
19  170.000000   9.000000  14.00000
20  161.000000  31.706376  50.00000
21  162.000000   5.000000  10.00000
22  180.000000   6.000000  11.00000
23  169.720689   7.000000  12.40191
24  175.000000   3.000000   6.00000

In [25]:
pip install miceforest

Collecting miceforest
  Downloading miceforest-6.0.5-py3-none-any.whl.metadata (34 kB)
Collecting lightgbm>=4.1.0 (from miceforest)
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from miceforest) (2.3.5)
Requirement already satisfied: pandas>=2.1.0 in c:\anaconda3\lib\site-packages (from miceforest) (2.3.3)
Requirement already satisfied: pyarrow>=6.0.1 in c:\anaconda3\lib\site-packages (from miceforest) (21.0.0)
Requirement already satisfied: scipy>=1.6.0 in c:\anaconda3\lib\site-packages (from miceforest) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda3\lib\site-packages (from pandas>=2.1.0->miceforest) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda3\lib\site-packages (from pandas>=2.1.0->miceforest) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\anaconda3\lib\site-packages (from pandas>=2.1.0->miceforest) (2025.2)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.0->miceforest) (1.17.0)
Downloading miceforest-6.0.5-py3-none-any.whl (38 kB)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------- ------------------ 0.8/1.5 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 5.5 MB/s  0:00:00
Installing collected packages: lightgbm, miceforest

   ---------------------------------------- 0/2 [lightgbm]
   ---------------------------------------- 0/2 [lightgbm]
   -------------------- ------------------- 1/2 [miceforest]
   -------------------- ------------------- 1/2 [miceforest]
   ---------------------------------------- 2/2 [miceforest]

Successfully installed lightgbm-4.6.0 miceforest-6.0.5
Note: you may need to restart the kernel to use updated packages.

In [26]:
import miceforest as mf

In [28]:
imp=mf.ImputationKernel(df)

In [29]:
imp.complete_data

<bound method ImputedData.complete_data of
              Class: ImputationKernel
            Datasets: 1
          Iterations: 0
        Data Samples: 25
        Data Columns: 3
   Imputed Variables: 3
   Modeled Variables: 3
All Iterations Saved: True
        >

In [31]:
df.ffill(axis=1)

    Height    YOE  Salary
0    175.0    3.0     6.0
1    168.0    4.0     9.0
2    160.0   10.0    18.0
3      NaN   15.0    25.0
4    161.0  161.0    50.0
5    162.0    5.0    10.0
6    180.0    6.0    11.0
7      NaN    7.0     7.0
8    172.0    8.0    12.0
9    170.0    9.0    14.0
10   175.0    3.0     6.0
11   168.0    4.0     9.0
12   160.0   10.0    18.0
13     NaN   15.0    25.0
14   161.0  161.0    50.0
15   162.0    5.0    10.0
16   180.0    6.0    11.0
17     NaN    7.0     7.0
18   172.0    8.0    12.0
19   170.0    9.0    14.0
20   161.0  161.0    50.0
21   162.0    5.0    10.0
22   180.0    6.0    11.0
23     NaN    7.0     7.0
24   175.0    3.0     6.0

In [32]:
df.bfill(axis=1)

    Height   YOE  Salary
0    175.0   3.0     6.0
1    168.0   4.0     9.0
2    160.0  10.0    18.0
3     15.0  15.0    25.0
4    161.0  50.0    50.0
5    162.0   5.0    10.0
6    180.0   6.0    11.0
7      7.0   7.0     NaN
8    172.0   8.0    12.0
9    170.0   9.0    14.0
10   175.0   3.0     6.0
11   168.0   4.0     9.0
12   160.0  10.0    18.0
13    15.0  15.0    25.0
14   161.0  50.0    50.0
15   162.0   5.0    10.0
16   180.0   6.0    11.0
17     7.0   7.0     NaN
18   172.0   8.0    12.0
19   170.0   9.0    14.0
20   161.0  50.0    50.0
21   162.0   5.0    10.0
22   180.0   6.0    11.0
23     7.0   7.0     NaN
24   175.0   3.0     6.0